before_install: npm install -g grunt-cli

sudo: false
language: node_js
node_js:
  - '8'
  - '6'
  - '4'
  - '0.8'
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
